### ISSUE TITLE
create_menu 的时候出错 sslv3 alert handshake failure

### ISSUE THREAD

**Issue by Raysmond** [lanrion/weixin_authorize#40]
```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure
	from /root/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:920:in `connect'
	from /root/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
	from /root/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /root/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:920:in `connect'
	from /root/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /root/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/rest_client-1.7.3/lib/restclient/request.rb:182:in `transmit'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/rest_client-1.7.3/lib/restclient/request.rb:68:in `execute'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/rest_client-1.7.3/lib/restclient/request.rb:35:in `execute'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/rest_client-1.7.3/lib/restclient.rb:69:in `get'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/weixin_authorize-1.0.1/lib/weixin_authorize/client.rb:55:in `http_get_without_token'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/weixin_authorize-1.0.1/lib/weixin_authorize/client.rb:34:in `authenticate'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/weixin_authorize-1.0.1/lib/weixin_authorize/client.rb:28:in `get_access_token'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/weixin_authorize-1.0.1/lib/weixin_authorize/client.rb:65:in `http_post'
	from /var/www/dvoy/shared/bundle/ruby/2.1.0/gems/weixin_authorize-1.0.1/lib/weixin_authorize/api/menu.rb:24:in `create_menu'
```

应该是之前SSL出现的漏洞导致，RestClient发送post请求出错，sslv3握手失败

**Comment by lanrion** [comment]
目前在众多使用者反馈中，没有收到这此的问题，可参考以下解决方案：
https://gist.github.com/fnichol/867550
https://ruby-china.org/topics/3324

**Comment by Raysmond** [comment]
之前在开发中遇到过类似的问题
我暂时使用`RestClient::Request.execute` 方法 指定ssl_version 为 `TLSv1` 或 `SSLv23 `

**Comment by lanrion** [comment]
可能跟你的本地环境有关，或者在你其他同事的机器上试试。

**Comment by lanrion** [comment]
见如下配置：
https://github.com/lanrion/weixin_authorize/wiki/config
